### ISSUE TITLE
Missing models with standard Gazebo installation

### ISSUE THREAD

**Issue by yyassa** [wingtra/sitl_gazebo#9]
Following the documentation i get the following error whenever I run gazebo: 
```
Error [parser.cc:575] Unable to find uri[model://sun]
Error [parser.cc:575] Unable to find uri[model://ground_plane]
```
(everything you insert just falls down to infinity because there is no ground_plane)

It seems like the standard gazebo models are not downloaded with `brew install gazebo6`. 

The only way I am able to resovle this is by copying the content of [this repo] (https://bitbucket.org/osrf/gazebo_models) into `~/.gazebo/models`.

Has anyone else experienced this on Mac OS?

**Comment by yyassa** [comment]
Running the standard PX4/Firmware with `make posix_sitl_default gazebo`. 
Rotors are not spinning, cannot really connect UDP through qgc,and I suspect this has to do with the models not correctly downloaded from the database.

Any help there?

**Comment by devbharat** [comment]
What do you observe, does the sitl terminal just show waiting for UDP data or is there any communication there ?

**Comment by yyassa** [comment]
```
[100%] Built target rotors_gazebo_multirotor_base_plugin
[init] shell id: 140735087604480
[init] task name: mainapp

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

Ready to fly.


pxh> INFO  Not using /dev/ttyACM0 for radio control input. Assuming joystick input via MAVLink.
INFO  Waiting for initial data on UDP. Please start the flight simulator to proceed..
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by LorenzMeier** [comment]
Try removing this line:
https://github.com/PX4/Firmware/blob/master/Tools/sitl_run.sh#L60

**Comment by yyassa** [comment]
Thanks this solves the models issue for me! (However no spinning rotors yet)
